language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.12.8
- 2.11.12
- 2.10.7
- 2.13.0-RC1
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
matrix:
  include:
  - scala: 2.12.8
    dist: xenial
    jdk: openjdk11
  - scala: 2.11.12
    env: JDK7_TEST
    script:
    - sbt "java++ 1.7" "++ ${TRAVIS_SCALA_VERSION}!" test
